### ISSUE TITLE
Exclude field only when reading or writing

### ISSUE THREAD

**Issue by vitornesello** [quinnj/JSON2.jl#13]
Is it possible to exclude a field only when reading or only when writing?
It might be interesting to have this feature when you have a matrix in your data structure. You may write its JSON form as an array (so you do not exclude when writing), but when reading you want to parse separately so you can convert it back to a matrix (excluding from reading).

**Comment by quinnj** [comment]
Hmmm, currently it's not possible, but in theory it wouldn't be too hard to support `excluderead` and `excludewrite` formatting options for custom types.
