### ISSUE TITLE
Change README to clarify JSON2 not available for Julia 0.6

### ISSUE THREAD

**Issue by non-Jedi** [quinnj/JSON2.jl#7]
Both released versions, 0.1.1 and 0.1.2 have `julia 0.7-` in their REQUIRES and so can't be used on 0.6. That's fine, but the current README gives the impression (says this is tested against 0.6) that this package works on 0.6.

**Comment by jamiecrcv** [comment]
Confirm, this is an issue.  Neither JSON2 nor LazyJSON work on 0.6, which is irritating in itself, but the documentation here needs to reflect that it's only available in 0.7

**Comment by Nosferican** [comment]
Close this issue? Nothing in README indicates it. For 0.6 use JSON.
